pybo/views/answer_views.py
from datetime import datetime

from flask import Blueprint, url_for, request, render_template, g
from werkzeug.utils import redirect

from .auth_views import login_required
from .. import db
from ..forms import AnswerForm
from ..models import Question, Answer

from flask import Blueprint, url_for, request, render_template, g, flash

bp = Blueprint('answer', __name__, url_prefix='/answer')


@bp.route('/create/<int:question_id>', methods=('POST',))
@login_required
def create(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content = request.form['content']
        answer = Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.commit()
        #return redirect(url_for('question.detail', question_id=question_id))
        return redirect('{}#answer_{}'.format(
            url_for('question.detail', question_id=question_id), answer.id))

    return render_template('question/question_detail.html', question=question, form=form)


@bp.route('/modify/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def modify(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    if g.user != answer.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=answer.question.id))
    if request.method == "POST":
        form = AnswerForm()
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date = datetime.now()  # 수정일시 저장
            db.session.commit()
            #return redirect(url_for('question.detail', question_id=answer.question.id))

            return redirect('{}#answer_{}'.format(
                url_for('question.detail', question_id=answer.question.id), answer.id))

    else:
        form = AnswerForm(obj=answer)
    return render_template('answer/answer_form.html', answer=answer, form=form)

@bp.route('/delete/<int:answer_id>')
@login_required
def delete(answer_id):
    answer = Answer.query.get_or_404(answer_id)
    question_id = answer.question.id
    if g.user != answer.user:
        flash('삭제권한이 없습니다')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', question_id=question_id))

pybo/views/question_views.py
from datetime import datetime

from flask import Blueprint, render_template, request, url_for, g
from werkzeug.utils import redirect

from .. import db
from ..forms import QuestionForm, AnswerForm
from ..models import Question
from ..views.auth_views import login_required

from flask import Blueprint, render_template, request, url_for, g, flash

from flask_ckeditor import CKEditor, CKEditorField


bp = Blueprint('question', __name__, url_prefix='/question')


@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)  # 페이지
    question_list = Question.query.order_by(Question.create_date.desc())
    question_list = question_list.paginate(page, per_page=10)
    return render_template('question/question_list.html', question_list=question_list)


@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    form = AnswerForm()
    question = Question.query.get_or_404(question_id)
    return render_template('question/question_detail.html', question=question, form=form)


@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():

    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question = Question(subject=form.subject.data, content=form.content.data,
                            create_date=datetime.now(), user=g.user)

        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('question/question_form.html', form=form)

@bp.route('/modify/<int:question_id>', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('수정권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    if request.method == 'POST':
        form = QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date = datetime.now() # 수정일시 저장
            db.session.commit()
            return redirect(url_for('question.detail', question_id=question_id))
    else:
        form = QuestionForm(obj=question)
    return render_template('question/question_form.html', form=form)

@bp.route('/delete/<int:question_id>')
@login_required
def delete(question_id):
    question = Question.query.get_or_404(question_id)
    if g.user != question.user:
        flash('삭제권한이 없습니다')
        return redirect(url_for('question.detail', question_id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

pybo/templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content|safe }}</div>
            <div class="d-flex justify-content-end">

                {% if question.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ question.modify_date|datetime }}</div>
                </div>
                {% endif %}

                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ question.user.username }}</div>
                    <div>{{ question.create_date|datetime }}</div>
                </div>
            </div>

           {% if g.user == question.user %}
           <div class="my-3">
               <a href="{{ url_for('question.modify', question_id=question.id) }}"
                   class="btn btn-sm btn-outline-secondary">Edit</a>

               <a href="#" class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{{ url_for('question.delete', question_id=question.id) }}">Delete</a>

           </div>
          {% endif %}

        </div>

    </div>
    <!-- <h5 class="border-bottom my-3 py-2">There are {{ question.answer_set|length }} comments.</h5> -->
    {% if question.answer_set|length > 1 %}
    <h5 class="border-bottom my-3 py-2">There are {{ question.answer_set|length }} comments.</h5>
    {% else %}
    <h5 class="border-bottom my-3 py-2">There is {{ question.answer_set|length }} comment.</h5>
    {% endif %}

    {% for answer in question.answer_set %}

    <a name="answer_{{ answer.id }}"></a>

    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">

                {% if answer.modify_date %}
                <div class="badge badge-light p-2 text-left mx-3">
                    <div class="mb-2">modified at</div>
                    <div>{{ answer.modify_date|datetime }}</div>
                </div>
                {% endif %}

                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.user.username }}</div>
                    <div>{{ answer.create_date|datetime }}</div>
                </div>
            </div>

             {% if g.user == answer.user %}
             <div class="my-3">
                <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                   class="btn btn-sm btn-outline-secondary">Edit</a>

                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                   data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}">Delete</a>

             </div>
            {% endif %}

        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        {{ form.csrf_token }}
        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <textarea {% if not g.user %}disabled{% endif %}
                    name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <!-- <input type="submit" value="Save Comment" class="btn btn-primary"> -->
        <button type="submit" class="btn btn-primary">Save Comment</button>

        <input type="text" id="word">
        <button type="button" class="btn btn-primary" onclick="openDictionary()">Search</button>
        <button type="button" class="btn btn-primary" onclick="openPapago()">Translate</button>


    </form>

</div>

<script>
    var inputWord = document.querySelector("#word");
    function openDictionary() {
        var newWin = window.open("https://dict.naver.com/enendict/english/#/search?query=" + inputWord.value, "", "left=600, top=0, width=500, height=600");
        if (newWin == null) {
            alert("팝업이 차단되어 있습니다. 팝업 차단을 해제하고 새로고침해 주세요.");
        }
        window.onload = openDictionary;
        document.querySelector("#word").value = "";
    }

    function openPapago() {
        var newWin = window.open("https://papago.naver.com/?sk=auto&tk=ko&hn=0&st="
                     + inputWord.value, "", "left=600, top=0, width=500, height=600");
        if (newWin == null) {
            alert("팝업이 차단되어 있습니다. 팝업 차단을 해제하고 새로고침해 주세요.");
        }
        window.onload = openDictionary;
        document.querySelector("#word").value = "";
    }

</script>

{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

pybo/templates/question/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container" xmlns:margin-left="http://www.w3.org/1999/xhtml"
     xmlns:margin-left="http://www.w3.org/1999/xhtml" xmlns:margin-left="http://www.w3.org/1999/xhtml">
    <!-- <h5 class="my-3 border-bottom pb-2">English Writing</h5> -->
    <form method="post" class="post-form my-2">
        {{ form.csrf_token }}

        <!-- 오류표시 Start -->
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
        {% endfor %}
        <!-- 오류표시 End -->

        <div class="form-group">
            <!-- <label for="subject">Title</label> -->
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.data or '' }}">
        </div>

        <div class="form-group">

            <!-- {{ form.content }} -->
            <!-- <label for="content">Content</label> -->
            <textarea class="form-control" name="content"
                      id="content" rows="11">{{ form.content.data or '' }}</textarea>

        </div>
        <button type="submit" class="btn btn-primary">Save</button>

        <span class="zoomBtnZone">
		    <button type="button" class="zoomOutBtn">-</button>
		    <button type="button" class="originBtn">16px</button>
		    <button type="button" class="zoomInBtn">+</button>
        </span>

    </form>
    <!-- {{ ckeditor.load(pkg_type='full') }} -->
	<!-- {{ ckeditor.config(name='content') }} -->

</div>
{% endblock %}

{% block script %}
<script>
    $(function(){
	    var baseFontSize = 16;
	    $(".zoomBtnZone button").on("click", zoomInOut);
	    function zoomInOut( ) {
		    if($(this).hasClass("zoomOutBtn")){
		    	if(baseFontSize<=12) return false;
			    baseFontSize--;
		    } else if($(this).hasClass("zoomInBtn")){
			    if(baseFontSize>=20) return false;
			    baseFontSize++;
		    } else {
			    baseFontSize = 16;
		    }
		    $(".originBtn").text(baseFontSize + "px");
		    $("#content").css({fontSize:baseFontSize + "px"});
	    }
    });
</script>
{% endblock %}

pybo/templates/question/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="text-center thead-white">
            <th>No</th>
            <th style="width:50%">Title</th>
            <th>Writer</th>
            <th>Date</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list.items %}
        <tr class="text-center">
            <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
            <td class="text-left">
                <a href="{{ url_for('question.detail', question_id=question.id) }}">{{ question.subject }}</a>
                {% if question.answer_set|length > 0 %}
                <span class="text-danger small ml-2">{{ question.answer_set|length }}</span>
                {% endif %}
            </td>
            <td>{{ question.user.username }}</td>  <!-- 글쓴이 추가 -->
            <td>{{ question.create_date|datetime }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">Not exist !</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{{ url_for('question.create') }}" class="btn btn-primary">English Writing</a>
</div>
{% endblock %}